services:
  - type: web
    name: xano-docs-rag
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker main:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /docs
    disk:
      name: chroma-data
      mountPath: /opt/render/project/src/chroma_db
      sizeGB: 1

